### ISSUE TITLE
Optimize readInt for "full" 8-bytes reads

### ISSUE THREAD

**Issue by raff** [blainsmith/seahash#5]
You can squeeze a few more ns (around 10ns/op on my mac) by optimizing readInt for "full" reads (8 bytes) like this:

    func readInt(b []uint8) uint64 {
    +        if len(b) == 8 {
    +            return binary.LittleEndian.Uint64(b)
    +        }
    +

**Comment by blainsmith** [comment]
Thanks for the recommendation! Simple to implement so I can get to it later on this week probably.

**Comment by blainsmith** [comment]
Got this implemented in v1.1.2. Thanks!
